### ISSUE TITLE
Missing conan

### ISSUE THREAD

**Issue by t413** [dockbuild/dockbuild#54]
Running the default example there seems to be no conan utility installed. Running `pip install conan` as a prerequisite won't work directly because the install destination isn't writable, using `pip install --user conan` seems to install it in a black hole that can't be found (it's not put in `~/.local/bin`).

I'm finding the same problem on dockcross so came here for a simpler setup to investigate. Any ideas? 

I depend on boost to build, what is the most idiomatic way here? I can see conan, apt/yum, or building the source in the mounted directory as options.

**Comment by jcfr** [comment]
both dockcross and dockbuild include a wrapper script name sudo (internally invoking `gosu`)

Running the following command complete ... 
```
sudo pip install conan
```

Last issue is that the python installed in dockbuild (and by extension dockcross) doesn't have sqlite:

```
conan --help
Traceback (most recent call last):
  File "/usr/local/bin/conan", line 11, in <module>
    load_entry_point('conan==1.8.2', 'console_scripts', 'conan')()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/site-packages/conans/conan.py", line 1, in <module>
    from conans.client.command import main
  File "/usr/local/lib/python3.6/site-packages/conans/client/command.py", line 10, in <module>
    from conans.client.conan_api import (Conan, default_manifest_folder)
  File "/usr/local/lib/python3.6/site-packages/conans/client/conan_api.py", line 23, in <module>
    from conans.client.rest.auth_manager import ConanApiAuthManager
  File "/usr/local/lib/python3.6/site-packages/conans/client/rest/auth_manager.py", line 19, in <module>
    from conans.client.cmd.user import update_localdb
  File "/usr/local/lib/python3.6/site-packages/conans/client/cmd/user.py", line 2, in <module>
    from conans.client.store.localdb import LocalDB
  File "/usr/local/lib/python3.6/site-packages/conans/client/store/localdb.py", line 2, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by jcfr** [comment]
this is observer with at least the ubuntu1804 and centos7 images

**Comment by jcfr** [comment]
Closing. 

In the context of `almalinux8-devtoolset14-gcc14` image, the following worked:

```
$ python -m pip install conan
python -m pip install conan 
Collecting conan
[...]
Successfully built conan patch-ng
Installing collected packages: urllib3, six, PyYAML, patch-ng, MarkupSafe, idna, fasteners, distro, colorama, charset_normalizer, certifi, requests, python-dateutil, Jinja2, conan
Successfully installed Jinja2-3.1.6 MarkupSafe-3.0.2 PyYAML-6.0.2 certifi-2025.7.14 charset_normalizer-3.4.2 colorama-0.4.6 conan-2.18.1 distro-1.8.0 fasteners-0.19 idna-3.10 patch-ng-1.18.1 python-dateutil-2.9.0.post0 requests-2.32.4 six-1.17.0 urllib3-2.0.7

$ conan --version 
Conan version 2.18.1
```
